repos:
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: requirements-txt-fixer
-   repo: https://github.com/cyyc1/py-def-indent-formatter
    rev: v0.1.4
    hooks:
    -   id: format-def-indent
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.0.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.3.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.38.2
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        args: [--config=.flake8]
